/**
 * @author
 * @since 8/17/2016
 */

(function () {
    'use strict';

    angular
        .module('amakkn')
        .factory('Factory', Factory);

    /* @ngInject */
    function Factory($log) {
        var factory = {};

        /// Factory Public API ///
        factory.method = method;
        ///////////////

        return factory;

        ///////////////

        function method() {
            // TODO autogenerated method stub...
        }
    }
})();
